// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var appear, items, offline, online, timeline, timelineUl, toggleBottom, toggleTop;
    timeline = $('#timeline');
    toggleTop = $("#toggleTop");
    toggleBottom = $("#toggleBottom");
    online = $('.online');
    offline = $('.offline');
    toggleTop.change(function() {
      if (this.checked) {
        toggleBottom.prop('checked', true);
        timeline.removeClass('showOnline', 300).removeClass('hideOffline', 300);
        online.fadeOut(300, function() {
          offline.fadeIn(300);
          return timeline.addClass('showOffline', 300);
        });
        return timeline.addClass('hideOnline', 300);
      } else {
        toggleBottom.prop('checked', false);
        timeline.removeClass('showOffline', 300).removeClass('hideOnline', 300);
        offline.fadeOut(300, function() {
          online.fadeIn(300);
          return timeline.addClass('showOnline', 300);
        });
        return timeline.addClass('hideOffline', 300);
      }
    });
    toggleBottom.change(function() {
      if (this.checked) {
        toggleTop.prop('checked', true);
        timeline.removeClass('showOnline', 300).removeClass('hideOffline', 300);
        online.fadeOut(300, function() {
          offline.fadeIn(300);
          return timeline.addClass('showOffline', 300);
        });
        return timeline.addClass('hideOnline', 300);
      } else {
        toggleTop.prop('checked', false);
        timeline.removeClass('showOffline', 300).removeClass('hideOnline', 300);
        offline.fadeOut(300, function() {
          online.fadeIn(300);
          return timeline.addClass('showOnline', 300);
        });
        return timeline.addClass('hideOffline', 300);
      }
    });
    $('.thumb').hover(function() {
      $(this).find('img').css('opacity', '0.05').wrap('<div class="tint"></div>');
      return $(this).find('figcaption').css('visibility', 'visible');
    }, function() {
      $(this).find('img').css('opacity', '1').unwrap();
      return $(this).find('figcaption').css('visibility', 'hidden');
    });
    appear = function(elem) {
      var elemFontSize;
      elemFontSize = elem.css('fontSize');
      return elem.animate({
        opacity: 1,
        fontSize: parseInt(elemFontSize) * 1.2
      }, 300, (function(_this) {
        return function() {
          return elem.animate({
            fontSize: elemFontSize
          }, 100);
        };
      })(this));
    };
    appear($('.fa-certificate'));
    setTimeout(function() {
      return appear($('.fa-bolt'));
    }, 600);
    setTimeout(function() {
      return $('.ribbon').animate({
        opacity: 1,
        top: 0
      }, 250);
    }, 1200);
    setTimeout(function() {
      return $('#timeline').animate({
        opacity: 1
      }, 800);
    }, 2000);
    timelineUl = timeline.find('ul');
    items = [];
    $.getJSON("projects.json").done(function(data) {
      $.each(data.items, function(i, item) {
        items.push(item);
        console.log(item);
        console.log(i);
        return console.log(items);
      });
      return $.each(items, function(i, item) {
        if (items[i].type === "event" && items[i].scope === "online") {
          return timelineUl.append(console.log('event append'), '<li class="group item online"> <!-- Event --> <section class="col-6 col-tab-12 col-ph-12 row event"> <div class="col-1 col-sm-2 col-ph-2 date"> <p>' + items[i].year + '</p> </div> <div class="col-11 col-sm-10 col-ph-10 eventText"> <h4 class="inlineBlock">' + items[i].title + '</h4> </div> </section> </li> <!-- event -->');
        } else if (items[i].type === "project" && items[i].scope === "online") {
          return timelineUl.append(console.log('project append'), '<li class="group item online"> <!-- Project --> <section class="col-6 col-tab-12 col-ph-12 row project "> <div class="col-1 col-sm-2 col-ph-2 date"> <p>' + items[i].year + '</p> </div> <figure class="col-7 col-sm-9 col-ph-9 thumb"> <img src="' + items[i].img + '" alt="' + items[i].imgAlt + '"/> <figcaption>' + items[i].description + '</figcaption> </figure> <div class="col-4 col-sm-9 col-ph-9 info"> <h3>' + items[i].title + '</h3> <ul class="extlinks inlineList"> <li><a href="' + items[i].extLink + '" target="_blank"><i class="fa fa-dribbble"></i></a></li> </ul> <ul class="skills"> <li><span>Design / UI / UX</span></li> <li><span>HTML5 / CSS3</span></li> <li><span>Bootstrap 3</span></li> <li><span>Google Search API</span></li> <li><span>JavaScript</span></li> </ul> </div> </section> </li> <!-- project -->');
        }
      });
    });
    $.fn.reverse = [].reverse;
    return setTimeout(function() {
      var listItems;
      listItems = $('#timeline > ul > li').reverse();
      return listItems.each(function(i) {
        console.log(i);
        return $(this).hide().delay(i * 2000).fadeIn(1000);
      });

      /*for i in listItems.length
        console.log listItems.length
        $('#timeline > ul > li:hidden:last').hide().delay(i*2000).fadeIn(1500)
       */
    }, 3500);
  });

}).call(this);

//# sourceMappingURL=script.js.map
