// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var appear, offline, online, timeline, toggleBottom, toggleTop;
    timeline = $('#timeline');
    toggleTop = $("#toggleTop");
    toggleBottom = $("#toggleBottom");
    online = $('.online');
    offline = $('.offline');
    toggleTop.change(function() {
      if (this.checked) {
        toggleBottom.prop('checked', true);
        timeline.removeClass('showOnline', 300).removeClass('hideOffline', 300);
        online.fadeOut(300, function() {
          offline.fadeIn(300);
          return timeline.addClass('showOffline', 300);
        });
        return timeline.addClass('hideOnline', 300);
      } else {
        toggleBottom.prop('checked', false);
        timeline.removeClass('showOffline', 300).removeClass('hideOnline', 300);
        offline.fadeOut(300, function() {
          online.fadeIn(300);
          return timeline.addClass('showOnline', 300);
        });
        return timeline.addClass('hideOffline', 300);
      }
    });
    toggleBottom.change(function() {
      if (this.checked) {
        toggleTop.prop('checked', true);
        timeline.removeClass('showOnline', 300).removeClass('hideOffline', 300);
        online.fadeOut(300, function() {
          offline.fadeIn(300);
          return timeline.addClass('showOffline', 300);
        });
        return timeline.addClass('hideOnline', 300);
      } else {
        toggleTop.prop('checked', false);
        timeline.removeClass('showOffline', 300).removeClass('hideOnline', 300);
        offline.fadeOut(300, function() {
          online.fadeIn(300);
          return timeline.addClass('showOnline', 300);
        });
        return timeline.addClass('hideOffline', 300);
      }
    });
    $('.thumb').hover(function() {
      $(this).find('img').css('opacity', '0.05').wrap('<div class="tint"></div>');
      return $(this).find('figcaption').css('visibility', 'visible');
    }, function() {
      $(this).find('img').css('opacity', '1').unwrap();
      return $(this).find('figcaption').css('visibility', 'hidden');
    });
    appear = function(elem) {
      var elemFontSize;
      elemFontSize = elem.css('fontSize');
      return elem.animate({
        opacity: 1,
        fontSize: parseInt(elemFontSize) * 1.2
      }, 300, (function(_this) {
        return function() {
          return elem.animate({
            fontSize: elemFontSize
          }, 100);
        };
      })(this));
    };
    appear($('.fa-certificate'));
    setTimeout(function() {
      return appear($('.fa-bolt'));
    }, 600);
    setTimeout(function() {
      return $('.ribbon').animate({
        opacity: 1,
        top: 0
      }, 250);
    }, 1200);
    return setTimeout(function() {
      return $('#timeline').animate({
        opacity: 1
      }, 1500);
    }, 2000);
  });

}).call(this);

//# sourceMappingURL=script.js.map
